import { withAuthAndRateLimit } from '@/lib/api/withAuthAndRateLimit';
import { NextRequest, NextResponse } from 'next/server';

export const GET = withAuthAndRateLimit(async (req, authCtx, props) => {
  const sourceTypes = [
    {
      id: 'file',
      nameAr: 'رفع الملفات المباشرة',
      nameEn: 'Local File Upload',
      category: 'files',
      descriptionAr: 'رفع مستندات PDF, DOCX, TXT, MD, CSV, JSON واستخراج النصوص وتجزئتها آلياً.',
      descriptionEn: 'Direct PDF, DOCX, TXT, MD, CSV, JSON upload with automated parsing & chunking.',
      iconName: 'FileText',
      defaultSchedule: 'manual',
      fields: [
        { key: 'chunkStrategy', labelAr: 'استراتيجية التقطيع', labelEn: 'Chunking Strategy', type: 'select', options: [
          { label: 'تقطيع دلالي محتذى (Semantic)', value: 'semantic' },
          { label: 'هيكل ماركداون (Markdown Structure)', value: 'markdown' },
          { label: 'نصوص وكود مصدري (Code / AST)', value: 'code' },
          { label: 'شريحة متداخلة (Sliding Window)', value: 'sliding' }
        ]},
        { key: 'chunkSize', labelAr: 'حجم القطعة (رمز/حرف)', labelEn: 'Chunk Size', type: 'number', required: true, default: 512 },
        { key: 'chunkOverlap', labelAr: 'التداخل بين القطع (%)', labelEn: 'Chunk Overlap %', type: 'number', required: true, default: 20 },
      ],
    },
    {
      id: 'url',
      nameAr: 'زاحف مواقع الويب وملاحة Sitemaps',
      nameEn: 'Web Crawler & Sitemap',
      category: 'web',
      descriptionAr: 'زحف أوتوماتيكي لصفحات الويب، دعم خريطة الموقع Sitemaps، وتصفية وسوم HTML.',
      descriptionEn: 'Automated web crawler supporting depth control, selectors & sitemaps.',
      iconName: 'Globe',
      defaultSchedule: '0 */6 * * *',
      fields: [
        { key: 'url', labelAr: 'رابط الموقع أو خريطة الموقع (URL/Sitemap)', labelEn: 'Target URL / Sitemap', type: 'text', required: true, placeholder: 'https://docs.example.com/sitemap.xml' },
        { key: 'maxDepth', labelAr: 'عمق الزحف الأقصى', labelEn: 'Max Crawl Depth', type: 'number', default: 3 },
        { key: 'maxPages', labelAr: 'الحد الأقصى للصفحات', labelEn: 'Max Pages Limit', type: 'number', default: 100 },
      ],
    },
    {
      id: 'rss',
      nameAr: 'تغذية الأخبار والمقالات (RSS / Atom)',
      nameEn: 'RSS / Atom Feed',
      category: 'web',
      descriptionAr: 'متابعة ومزامنة التحديثات الدورية من موجزات الأخبار ومدونات الشركات.',
      descriptionEn: 'Continuous ingestion from RSS/Atom channels and company blogs.',
      iconName: 'Rss',
      defaultSchedule: '0 */1 * * *',
      fields: [
        { key: 'feedUrl', labelAr: 'رابط التغذية RSS/Atom', labelEn: 'Feed URL', type: 'text', required: true, placeholder: 'https://news.example.com/feed.xml' },
      ],
    },
    {
      id: 'youtube',
      nameAr: 'تفريغ مقاطع وقنوات يوتيوب (YouTube Transcript)',
      nameEn: 'YouTube Transcript & Video Summarizer',
      category: 'web',
      descriptionAr: 'استخراج وتفريغ نصوص الفيديو مع الطوابع الزمنية وإمكانية الترجمة الفورية.',
      descriptionEn: 'Automatic subtitle extraction with timestamps and auto-translation.',
      iconName: 'Youtube',
      defaultSchedule: '0 0 * * *',
      fields: [
        { key: 'channelOrVideoUrl', labelAr: 'رابط الفيديو أو القائمة', labelEn: 'Video/Playlist URL', type: 'text', required: true, placeholder: 'https://youtube.com/watch?v=...' },
        { key: 'autoTranslateArabic', labelAr: 'ترجمة تلقائية للعربية', labelEn: 'Auto translate to Arabic', type: 'select', options: [{ label: 'نعم', value: 'true' }, { label: 'لا', value: 'false' }] },
      ],
    },
    {
      id: 'github',
      nameAr: 'مستودعات الكود (GitHub / GitLab)',
      nameEn: 'GitHub / GitLab Repositories',
      category: 'workplace',
      descriptionAr: 'قراءة وفهرسة أودية الكود المصدري، التوثيقات، والملفات البرمجية.',
      descriptionEn: 'Index source code, READMEs, pull requests, and documentation.',
      iconName: 'Github',
      defaultSchedule: '0 */3 * * *',
      fields: [
        { key: 'repo', labelAr: 'اسم المستودع (Owner/Repo)', labelEn: 'Repository Name', type: 'text', required: true, placeholder: 'owner/repository' },
        { key: 'branch', labelAr: 'الفرع المستهدف (Branch)', labelEn: 'Target Branch', type: 'text', default: 'main' },
        { key: 'personalToken', labelAr: 'رمز الوصول الشخصي (Access Token)', labelEn: 'Personal Access Token', type: 'password', required: false },
      ],
    },
    {
      id: 'notion',
      nameAr: 'مساحات عمل Notion Workspace',
      nameEn: 'Notion Workspace',
      category: 'workplace',
      descriptionAr: 'مزامنة صفحات وقواعد بيانات Notion المحدثة لحظياً.',
      descriptionEn: 'Sync Notion pages and databases seamlessly.',
      iconName: 'BookOpen',
      defaultSchedule: '0 */4 * * *',
      fields: [
        { key: 'integrationToken', labelAr: 'رمز الدمج (Notion Internal Token)', labelEn: 'Notion Integration Secret', type: 'password', required: true },
        { key: 'databaseOrPageId', labelAr: 'معرف الصفحة أو قاعدة البيانات', labelEn: 'Page / Database ID', type: 'text', required: true },
      ],
    },
    {
      id: 'gdrive',
      nameAr: 'مجلدات Google Drive & Docs',
      nameEn: 'Google Drive & Google Docs',
      category: 'cloud',
      descriptionAr: 'ربط مجلدات Google Drive واستخراج المستندات والجداول تلقائياً.',
      descriptionEn: 'Sync Google Drive folders, Google Docs, Sheets & Presentations.',
      iconName: 'Folder',
      defaultSchedule: '0 */12 * * *',
      fields: [
        { key: 'folderId', labelAr: 'معرف مجلد Google Drive (Folder ID)', labelEn: 'Google Drive Folder ID', type: 'text', required: true },
      ],
    },
    {
      id: 'confluence',
      nameAr: 'وثائق ومساحات Confluence',
      nameEn: 'Atlassian Confluence Space',
      category: 'workplace',
      descriptionAr: 'فهرسة صفحات Wiki الموثقة بفرق العمل والمشاريع.',
      descriptionEn: 'Index Atlassian Confluence spaces and enterprise wikis.',
      iconName: 'Layers',
      defaultSchedule: '0 */6 * * *',
      fields: [
        { key: 'domain', labelAr: 'نطاق Atlassian (e.g. company.atlassian.net)', labelEn: 'Atlassian Site Domain', type: 'text', required: true },
        { key: 'spaceKey', labelAr: 'مفتاح المساحة (Space Key)', labelEn: 'Space Key', type: 'text', required: true },
        { key: 'apiToken', labelAr: 'رمز API Token', labelEn: 'API Token', type: 'password', required: true },
      ],
    },
    {
      id: 'slack',
      nameAr: 'قنوات ومحادثات Slack & Discord',
      nameEn: 'Slack Channels & Conversations',
      category: 'workplace',
      descriptionAr: 'أرشفة وفهرسة النقاشات وقنوات الدعم الفني للاستعلام الذكي.',
      descriptionEn: 'Ingest team conversations and support channels.',
      iconName: 'MessageSquare',
      defaultSchedule: '0 */2 * * *',
      fields: [
        { key: 'channelId', labelAr: 'معرف القناة (Channel ID)', labelEn: 'Channel ID', type: 'text', required: true },
        { key: 'botToken', labelAr: 'رمز Slack Bot Token', labelEn: 'Slack Bot Token (xoxb-...)', type: 'password', required: true },
      ],
    },
    {
      id: 'email',
      nameAr: 'صندوق البريد الإلكتروني (IMAP / Gmail)',
      nameEn: 'Email Inbox (IMAP / Gmail)',
      category: 'workplace',
      descriptionAr: 'قراءة الرسائل والملفات المرفقة وتصفية الاتصالات الهامة.',
      descriptionEn: 'Ingest email threads and attached documents via IMAP/Gmail API.',
      iconName: 'Mail',
      defaultSchedule: '0 */2 * * *',
      fields: [
        { key: 'emailAddress', labelAr: 'عنوان البريد الإلكتروني', labelEn: 'Email Address', type: 'text', required: true },
        { key: 'imapServer', labelAr: 'خادم IMAP', labelEn: 'IMAP Hostname', type: 'text', default: 'imap.gmail.com' },
      ],
    },
    {
      id: 'database',
      nameAr: 'قواعد البيانات الخارجية (PostgreSQL / MySQL / MongoDB)',
      nameEn: 'External Databases (PostgreSQL / MySQL / MongoDB)',
      category: 'databases',
      descriptionAr: 'تشغيل استعلامات حتمية ومزامنة الجداول والسجلات التراكمية.',
      descriptionEn: 'Query and stream structured rows from PostgreSQL, MySQL or MongoDB.',
      iconName: 'Database',
      defaultSchedule: '*/30 * * * *',
      fields: [
        { key: 'dbType', labelAr: 'نوع قاعدة البيانات', labelEn: 'Database Engine', type: 'select', options: [
          { label: 'PostgreSQL', value: 'postgresql' },
          { label: 'MySQL / MariaDB', value: 'mysql' },
          { label: 'MongoDB', value: 'mongodb' }
        ]},
        { key: 'host', labelAr: 'عنوان الخادم (Host)', labelEn: 'Host', type: 'text', required: true, placeholder: 'db.internal.company.com' },
        { key: 'port', labelAr: 'المنفذ (Port)', labelEn: 'Port', type: 'number', default: 5432 },
        { key: 'database', labelAr: 'اسم قاعدة البيانات', labelEn: 'Database Name', type: 'text', required: true },
        { key: 'syncQuery', labelAr: 'استعلام المزامنة (SQL Sync Query)', labelEn: 'SQL Sync Query', type: 'textarea', placeholder: 'SELECT id, title, content FROM docs WHERE updated_at > :last_sync' },
      ],
    },
    {
      id: 'api',
      nameAr: 'نقطة نهاية مخصصة (REST / GraphQL API)',
      nameEn: 'Custom REST / GraphQL Endpoint',
      category: 'databases',
      descriptionAr: 'ربط أنظمة ERP/CRM عبر نقاط API مخصصة مع دعم الترويسات والتوثيق.',
      descriptionEn: 'Connect ERP/CRM APIs with custom headers and JSON payload extraction.',
      iconName: 'Code',
      defaultSchedule: '0 */6 * * *',
      fields: [
        { key: 'endpointUrl', labelAr: 'رابط Endpoint URL', labelEn: 'Endpoint URL', type: 'text', required: true, placeholder: 'https://api.company.com/v1/knowledge' },
        { key: 'httpMethod', labelAr: 'طريقة HTTP', labelEn: 'HTTP Method', type: 'select', options: [{ label: 'GET', value: 'GET' }, { label: 'POST', value: 'POST' }] },
        { key: 'headersJson', labelAr: 'ترويسات الطلب Headers (JSON)', labelEn: 'JSON Headers', type: 'textarea', placeholder: '{"Authorization": "Bearer ...", "Accept": "application/json"}' },
      ],
    },
  ];

  return NextResponse.json({ sourceTypes });
});
